name: prueba_tecnica
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.11
  table_calendar: ^3.0.0
  equatable: ^2.0.0
  flutter_bloc: ^8.1.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

